/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { EditorPickList200Data } from './editorPickList200Data';

export type EditorPickList200 = {
  data?: EditorPickList200Data;
};
