/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { EditorPickList200DataPicksItem } from './editorPickList200DataPicksItem';

export type EditorPickList200Data = {
  date?: string;
  picks?: EditorPickList200DataPicksItem[];
};
