/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type EpisodeType = typeof EpisodeType[keyof typeof EpisodeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EpisodeType = {
  EPISODE: 'EPISODE',
} as const;
