/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type EpisodeStatus = typeof EpisodeStatus[keyof typeof EpisodeStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EpisodeStatus = {
  NORMAL: 'NORMAL',
} as const;
