/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { InboxList200LoadMoreKey } from './inboxList200LoadMoreKey';
import type { Episode } from './episode';

export type InboxList200 = {
  loadMoreKey?: InboxList200LoadMoreKey;
  data?: Episode[];
};
