/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { LoginWithSMS200DataNewbieGuideFeatureGroup } from './loginWithSMS200DataNewbieGuideFeatureGroup';
import type { LoginWithSMS200DataSubscriptionGuideFeatureGroup } from './loginWithSMS200DataSubscriptionGuideFeatureGroup';
import type { User } from './user';

export type LoginWithSMS200Data = {
  isSignUp?: boolean;
  showNewbieGuide?: boolean;
  newbieGuideFeatureGroup?: LoginWithSMS200DataNewbieGuideFeatureGroup;
  subscriptionGuideFeatureGroup?: LoginWithSMS200DataSubscriptionGuideFeatureGroup;
  user?: User;
};
