/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type LoginWithSMS400 = {
  success?: boolean;
  code?: number;
  toast?: string;
};
