/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { PhoneNumber } from './phoneNumber';
import type { LoginWithSMSBodyAllOf } from './loginWithSMSBodyAllOf';

export type LoginWithSMSBody = PhoneNumber & LoginWithSMSBodyAllOf;
