/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type LoginWithSMS200DataNewbieGuideFeatureGroup = typeof LoginWithSMS200DataNewbieGuideFeatureGroup[keyof typeof LoginWithSMS200DataNewbieGuideFeatureGroup];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginWithSMS200DataNewbieGuideFeatureGroup = {
  SKIP: 'SKIP',
} as const;
