/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { LoginWithSMS200Data } from './loginWithSMS200Data';

export type LoginWithSMS200 = {
  data?: LoginWithSMS200Data;
};
