/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type LoginWithSMS200DataSubscriptionGuideFeatureGroup = typeof LoginWithSMS200DataSubscriptionGuideFeatureGroup[keyof typeof LoginWithSMS200DataSubscriptionGuideFeatureGroup];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginWithSMS200DataSubscriptionGuideFeatureGroup = {
  DISABLED: 'DISABLED',
} as const;
