/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { MediaSourceMode } from './mediaSourceMode';

export interface MediaSource {
  mode?: MediaSourceMode;
  url?: string;
}
