/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type MediaSourceMode = typeof MediaSourceMode[keyof typeof MediaSourceMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaSourceMode = {
  PUBLIC: 'PUBLIC',
} as const;
