/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { MediaSource } from './mediaSource';

export interface Media {
  id?: string;
  size?: number;
  mimeType?: string;
  source?: MediaSource;
  backupSource?: MediaSource;
}
