/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type PodcastStatus = typeof PodcastStatus[keyof typeof PodcastStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PodcastStatus = {
  NORMAL: 'NORMAL',
} as const;
