/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type PodcastSyncMode = typeof PodcastSyncMode[keyof typeof PodcastSyncMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PodcastSyncMode = {
  RSS: 'RSS',
} as const;
