/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type PodcastType = typeof PodcastType[keyof typeof PodcastType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PodcastType = {
  PODCAST: 'PODCAST',
} as const;
