/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { PodcastType } from './podcastType';
import type { Image } from './image';
import type { Color } from './color';
import type { PodcastSyncMode } from './podcastSyncMode';
import type { PodcastSubscriptionStatus } from './podcastSubscriptionStatus';
import type { PodcastStatus } from './podcastStatus';
import type { User } from './user';

export interface Podcast {
  type?: PodcastType;
  pid?: string;
  title?: string;
  author?: string;
  description?: string;
  subscriptionCount?: number;
  /** Podcast image */
  image?: Image;
  /** Podcast colors */
  color?: Color;
  syncMode?: PodcastSyncMode;
  episodeCount?: number;
  latestEpisodePubDate?: string;
  subscriptionStatus?: PodcastSubscriptionStatus;
  subscriptionPush?: boolean;
  subscriptionStar?: boolean;
  status?: PodcastStatus;
  payEpisodeCount?: number;
  podcasters?: User[];
}
