/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type PodcastSubscriptionStatus = typeof PodcastSubscriptionStatus[keyof typeof PodcastSubscriptionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PodcastSubscriptionStatus = {
  OFF: 'OFF',
  ON: 'ON',
} as const;
