/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type UserGender = typeof UserGender[keyof typeof UserGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserGender = {
  MALE: 'MALE',
  FEAMALE: 'FEAMALE',
} as const;
