/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@sveltestack/svelte-query'
import type {
  UseMutationOptions,
  MutationFunction
} from '@sveltestack/svelte-query'
import type {
  EditorPickList200,
  Error,
  EditorPickListBody
} from '.././model'
import { client } from '../../client'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


/**
 * @summary Number of editor picks
 */
export const editorPickList = (
    editorPickListBody: EditorPickListBody,
 ) => {
      return client<EditorPickList200>(
      {url: `/editor-pick/list`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: editorPickListBody
    },
      );
    }
  


    export type EditorPickListMutationResult = NonNullable<Awaited<ReturnType<typeof editorPickList>>>
    export type EditorPickListMutationBody = EditorPickListBody
    export type EditorPickListMutationError = Error

    export const useEditorPickList = <TError = Error,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editorPickList>>, TError,{data: EditorPickListBody}, TContext>, }
) => {
      const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editorPickList>>, {data: EditorPickListBody}> = (props) => {
          const {data} = props ?? {};

          return  editorPickList(data,)
        }

      return useMutation<Awaited<ReturnType<typeof editorPickList>>, TError, {data: EditorPickListBody}, TContext>(mutationFn, mutationOptions)
    }
    